spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://HRUTHIC;databaseName=ouction_system;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: komuravellirakshitha50@gmail.com
    password: nnht nbwz rqle losh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080



